#!/bin/bash

case "$1" in
  114)
    DNS=114.114.114.114
    ;;
  ali)
    DNS=223.5.5.5
    ;;
  baidu)
    DNS=180.76.76.76
    ;;
  cnnic)
    DNS=1.2.4.8
    ;;
  dnspod)
    DNS=119.29.29.29
    ;;
  google)
    DNS=8.8.8.8
    ;;
  163)
    DNS=104.236.189.178
    ;;
  *)
    DNS=$1
esac

sed -i "s|^\(server.*\)/[^/]*$|\1/$DNS|" accelerated-domains.china.conf
