#!/bin/bash

case "$1" in
  114)
    DNS=114.114.114.114
    ;;
  ali)
    DNS=223.5.5.5
    ;;
  cnnic)
    DNS=1.2.4.8
    ;;
  baidu)
    DNS=180.76.76.76
    ;;
  google)
    DNS=8.8.4.4
    ;;
  *)
    DNS=$1
esac

sed -i "s|^\(server.*\)/[^/]*$|\1/$DNS|" /usr/local/etc/dnsmasq.d/accelerated-domains.china.conf
